sudo: required
dist: trusty
language: bash
env:
  - DOKKU_LOCK_PATH=/var/lock/dokku-daemon/dokku-daemon.lock DOKKU_SOCK_PATH=/var/run/dokku-daemon/dokku-daemon.sock
before_install:
        - wget https://raw.githubusercontent.com/dokku/dokku/v0.4.9/bootstrap.sh && sudo DOKKU_TAG="v0.4.9" bash bootstrap.sh
install:
        - sudo make ci-dependencies install
        - sudo initctl reload-configuration
        - sleep 5
script:
        - make test
